name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: yarn install
        run: yarn install
      - name: eslint
        run: yarn lint
      - name: test
        run: yarn test
