name: test

on: 
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Execute tests
        uses: actions/checkout@v2
      
      - name: Run yarn install
        working-directory: ./core
        run: yarn install
      - name: Run lint
        working-directory: ./core
        run: yarn lint
      - name: Run test
        working-directory: ./core
        run: yarn test
